[package]
name = "c2p"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.25.5", default-features = false, features = ["png", "jpeg", "bmp", "webp"] }
miniz_oxide = { version = "0.8.5", default-features = false }
